# Use a lightweight Python base image
FROM python:3.10-slim-buster

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all your application files (main.py, .env, gcp_creds_application.json, etc.)
# into the container's /app directory.
COPY . .

# Expose the port FastAPI runs on
EXPOSE 8000

# The command to run the application when the container starts
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]